### ISSUE TITLE
Segmentation Fault in example

### ISSUE THREAD

**Issue by SimonCadge** [UberLambda/ttspico-rs#2]
I'm interested in using this crate so I've tried to compile the example code on my mac and I'm getting a segmentation error.
My cargo.toml file looks like this:
```
[package]
name = "RustGame"
version = "0.1.0"
authors = ["SimonCadge <SimonHCadge@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "*"
ttspico = "*"
```
Initially I had a different error where it failed to load the files in "ttspico-sys/build/pico/lang/". This folder doesn't seem to be built at all when building ttspico-sys, you can see below that the /pico/lib folder is built but the /pico/lang folder doesn't appear. I don't know whether this is intended or not.
![Screenshot 2020-04-11 at 13 53 27](https://user-images.githubusercontent.com/11338764/79044253-01c6c400-7bfc-11ea-937f-f68d5f27ddb2.png)
Since the files weren't built automatically I decided that the other option would be downloading them from github directly, which I did. I now have the /pico/lang folder in the same folder as my cargo.toml file and I've pointed the code to look for the 'en-US_ta.bin' and the 'en-US_lh0_sg.bin' in that folder. It successfully finds the files, which you can see because it prints out the line `TA: en-US_ta_1.1.0.0-0-2, SG: en-US_lh0_sg_1.1.0.0-0-2`, but it then breaks with a segmentation fault.
![Screenshot 2020-04-11 at 13 57 36](https://user-images.githubusercontent.com/11338764/79044332-6d109600-7bfc-11ea-87e0-14ce58976e9c.png)
I would assume that this is the case because those files were built for a different system and so when it tries to load them they're in the wrong format or something. If this is the case then how do I get ttspico-sys to build properly?

**Comment by SimonCadge** [comment]
This problem also occurred when trying to run the hello world code in linux using WSL. As such I imagine that it's the building process which is confusing rather than the code.  
If there is any documentation on how to properly build and use the crate please point me to it.

**Comment by UberLambda** [comment]
Hello, sorry for the delay (I did not see the notification...)
I haven't tested this crate on anything but Manjaro x64, and `cargo run --example hello` works fine on my machine.  
When testing locally, segfaults from Pico usually were due to resources files not being loaded correctly by the engine. All "missing files" conditions should be wrapped by panics though, so I'm not really sure what's going on here -  I sadly don't have access to a Mac OS machine, so I can't investigate further...

I agree that the buildsystem is very confusing. This crate was just a testbench for me getting used to Rust, so I thought gluing a C library (& its build system) would make me feel more at home :)

**Comment by UberLambda** [comment]
Quick update, it seems like `cpal` does not like when another PulseAudio stream is playing on my end - resulting in a segfault down the line.  
I think a lot of problems could be fixed by replacing that dependency with something else for the examples (maybe just outputting to a .wav file) - I'll see what I can do when I get the time.

**Comment by SimonCadge** [comment]
Ok, so I tried compiling it on windows just by cloning the whole repo and using `cargo run --example hello` and that compiled successfully but then cpal itself broke. And I've been trying to get the cpal examples themselves working and it seems like it is just broken.
I'm going to try and see whether I can get ttspico-rs working with Amethyst though.

**Comment by SimonCadge** [comment]
Ok, so I've commented out the line `audio_out(&*pcm_data):` and replaced it with the line `println!("{:?}", pcm_data);`. This works now and I'm successfully printing the pcm data but then the process hangs for a second before breaking with the error:
![image](https://user-images.githubusercontent.com/11338764/79162361-05fa0980-7dd5-11ea-8c90-37da03932ccf.png)
Do you know why this happens? It means that I can't generate audio inside another application because this error will just break the application.

**Comment by SimonCadge** [comment]
I've changed the code to use hound and save the pcm data to a wav file.
![image](https://user-images.githubusercontent.com/11338764/79165597-596f5600-7ddb-11ea-9550-aaf0539cbaee.png)
This works and the wav file does include the audio data correctly.
Unfortunately the STATUS_ACCESS_VIOLATION crash is still an issue. Any idea on how to fix that?

**Comment by UberLambda** [comment]
@SimonCadge Not really, sorry. I will try and investigate as soon as I get the time to on my Windows machine.

I assume the main culprit would be the hacky patches I had to do to Pico to make it work on 64-bit machines. I basically just replaced every `void* -> uint32_t` cast that was there in the code with proper `uintptr_t`s, I wonder if that broke something? It worked fine on Linux but it seems like it does not on other platforms for some reason.

**Comment by SimonCadge** [comment]
Are you sure it works fine on Linux though? When I added the line `std::process::exit(0)` to the end of the hello.rs code it causes the process to exit without throwing an error. `std::process::exit(0)` is called in the `audio_out` function when the output stream is empty, so I wonder whether you just don't see the error because you're quitting the program before it happens.  
I think the problem might be because you don't seem to have implemented the second half of the pico engine in your high level bindings. ttspico_sys has functions like pico_disposeEngine which I don't think you're using in ttspico, and the pico documentation [here](https://github.com/DougGore/picopi/blob/master/pico_resources/docs/SVOX_Pico_Manual.pdf) (page 11) describes how you're supposed to set up the pico system, use it and then break it down again.  
If you're not doing that then I assume that the problem is caused by rust trying to clean up something that pico is still using.

**Comment by UberLambda** [comment]
@SimonCadge I scavenged a bit into Pico code and there was a `size_t` being set to exactly `2**32` on Windows (causing the example to crash & burn on `System::drop()` when it tried to deallocate memory). I patched it and it seemed to ouput PCM data to console fine on Windows, so hopefully it works now!

Can I use your code snippet above in hello.rs to output to WAV instead of to CPAL (or, even better, could you please merge it to master?). Cheers!

**Comment by SimonCadge** [comment]
Certainly :)
I tried it and it does seem that your change has fixed the problem.
I also upgraded the version of cpal in the cargo.toml file to 0.11 and that seems to have worked. Unfortunately since I'm on windows and cpal uses wasapi which only supports a single output format for each device cpal can't actually play the files unless they're changed to a sample rate of 48000. So instead I'm going to make two versions of the example, one which uses cpal and should still work fine on linux and mac, and another that uses hound to create the wav file, which should work everywhere.
